fix: update forkCount back to 0, since setting it to 1 might be crashing the CI
Error:  Error occurred during initialization of VM
Warning:  Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/sauce-lab-the-internet/sauce-lab-the-internet/target/surefire-reports/2023-07-18T23-17-11_742-jvmRun1.dumpstream